### ISSUE TITLE
Build up of observations & SSH login details

### ISSUE THREAD

**Issue by TechMindsYT** [dernasherbrezon/r2cloud#138] opened 2023-05-20 21:36 UTC
Hi all,

I have a new install  which has been working okay until today. Now the observations are just saying "decoding", around 30 of them.

I want to SSH into the pi to try to find the logs, but I the standard pi / raspberry does not work.

I am using the latest R2Cloud image downloaded from Github.

Thanks

**Comment by dernasherbrezon** [comment] 2023-05-20 21:58
Hi,

I think ssh login by default is disable on all RPi images. r2cloud image is based on the official hence SSH disabled also. Can you turn on SSH-server if you mount SD card into your PC and create a file named "ssh" there, unmount and insert back into RPi. Can't find the recent guide about it, but it always worked. 

Once on the host, you can check logs using the command ```journalctl -u r2cloud -n 200``` or ```journalctl -u r2cloud -n 800```.

**Comment by TechMindsYT** [comment] 2023-05-20 22:07
> Hi,
> 
> I think ssh login by default is disabled on all RPi images. r2cloud image is based on the official hence SSH disabled also. You can turn on SSH-server if you:
> 
> * mount SD card into your PC
> * create a file named "ssh" there
> * unmount
> * insert back into RPi.
> 
> Can't find the recent guide about it, but it always worked.
> 
> Once on the host, you can check logs using the command `journalctl -u r2cloud -n 200` or `journalctl -u r2cloud -n 800`.

Well, that's the thing, I have done that to gain access via SSH using Putty, but when presented with the username and password the default "pi" and "raspberry" do not appear to work. So, I was wondering if someone know what it is?

Thanks

**Comment by dernasherbrezon** [comment] 2023-05-20 22:53
r2cloud image don't have anything specific to SSH. Here is the repo btw: https://github.com/dernasherbrezon/pi-gen

**Comment by TechMindsYT** [comment] 2023-05-21 14:47
How do I fix this if I cannot SSH?

I want to promote this useful application on my YouTube channel, but I cant unless I can fix this.

![image](https://github.com/dernasherbrezon/r2cloud/assets/10533694/2955ae30-bc58-4f81-94ac-3a1f1012cceb)

**Comment by dernasherbrezon** [comment] 2023-05-21 15:00
Hi, it seems the issue is related to https://github.com/dernasherbrezon/r2cloud/issues/136 . It was fixed in December 2022. Are you using the latest image? Without logs it's really hard to troubleshoot. 

There was some update in recent RPi images. Can you try:

```
There are also mechanisms to preconfigure an image without using Imager. To set up a user on first boot and bypass the wizard completely, create a file called userconf or userconf.txt in the boot partition of the SD card; this is the part of the SD card which can be seen when it is mounted in a Windows or MacOS computer.
```

More details at https://www.raspberrypi.com/news/raspberry-pi-bullseye-update-april-2022/

**Comment by TechMindsYT** [comment] 2023-05-21 15:02
is there a way to access the logs?

To confirm I am using the latest pre-built image downloaded from this github.

**Comment by dernasherbrezon** [comment] 2023-05-21 15:07
No, logs might contain secure information, thus no access without username and password :)

Let me test SSH access on the latest image.

**Comment by dernasherbrezon** [comment] 2023-05-21 15:40
Yes, they removed default username and password from images. To use pi you need:

1. Mount SD card into PC
2. Create a file userconf.txt there
3. Put ```pi:$6$XVh7/PVvihco7hhw$NwS6PHSyf3.MUvd6kdS7l997YpQNAXhsmjR2rQ8zMCqJMAdrjirbXpigFHx/ytx3huiOMxI21xfBjAEOTD3QU/``` 
4. Login via SSH using username "pi" and old password.

Once logged in, can you please check logs and attach here?

**Comment by TechMindsYT** [comment] 2023-05-21 19:44
Hi, thanks, I can now access the Pi via SSH.

However, where are the logs located? Could you please provide the path and filename to the log file please?

Thanks

**Comment by dernasherbrezon** [comment] 2023-05-22 07:02
Once on the host, you can check logs using the command ```journalctl -u r2cloud -n 200``` or ```journalctl -u r2cloud -n 800```. More troubleshooting tips in the documentation: https://github.com/dernasherbrezon/r2cloud/wiki/Troubleshooting-guide

**Comment by dernasherbrezon** [comment] 2023-06-02 09:25
Do you still see the issue? You can join telegram channel where we can troubleshoot the issue live: https://t.me/leosatdata

**Closed** 2023-06-23 06:26 UTC
